version: '3.8'
services:
  db:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data

      
  webserver:
    image: my-airflow-job:latest
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    command: webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    depends_on:
      - db

  scheduler:
    image: my-airflow-job:latest
    container_name: airflow-scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    depends_on:
      - db
      
volumes:
  airflow-db-data:
